/* Generated by scripts/optimize-assets.mjs. Do not hand-edit dimensions. */
export const assetMeta = {
  "logo": {
    "width": 1024,
    "height": 1024
  },
  "banner": {
    "width": 1024,
    "height": 341
  },
  "telegram": {
    "width": 1024,
    "height": 483
  }
} as const;
