import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import sharp from 'sharp';

const originalDir = path.resolve('public/assets/originals');
const outDir = path.resolve('public/assets');

const sources = {
  logo: path.join(originalDir, 'nwdog-logo-full.jpg'),
  banner: path.join(originalDir, 'nwdog-banner.jpg'),
  telegram: path.join(originalDir, 'nwdog-tg-banner.jpg'),
};

await mkdir(outDir, { recursive: true });

async function raster(input, filename) {
  const image = sharp(input);
  const meta = await image.metadata();
  const base = path.join(outDir, filename);
  await image.clone().webp({ quality: 82 }).toFile(`${base}.webp`);
  await image.clone().avif({ quality: 48 }).toFile(`${base}.avif`);
  return { width: meta.width ?? 0, height: meta.height ?? 0 };
}

await sharp(sources.logo).png({ compressionLevel: 9 }).toFile(path.join(outDir, 'nwdog-logo-full.png'));
const logo = await raster(sources.logo, 'nwdog-logo-full');

await sharp(sources.banner).jpeg({ quality: 86, mozjpeg: true }).toFile(path.join(outDir, 'nwdog-banner.jpg'));
const banner = await raster(sources.banner, 'nwdog-banner');

await sharp(sources.telegram).jpeg({ quality: 86, mozjpeg: true }).toFile(path.join(outDir, 'nwdog-tg-banner.jpg'));
const telegram = await raster(sources.telegram, 'nwdog-tg-banner');

await sharp(sources.banner)
  .resize({ width: 1200, withoutEnlargement: true })
  .jpeg({ quality: 82, mozjpeg: true })
  .toFile(path.join(outDir, 'og.jpg'));

await sharp(sources.logo).resize(32, 32).png().toFile(path.join(outDir, 'favicon-32.png'));
await sharp(sources.logo).resize(180, 180).png().toFile(path.join(outDir, 'apple-touch.png'));

const meta = { logo, banner, telegram };
await writeFile(
  path.resolve('src/config/assetMeta.ts'),
  `/* Generated by scripts/optimize-assets.mjs. Do not hand-edit dimensions. */\nexport const assetMeta = ${JSON.stringify(meta, null, 2)} as const;\n`,
);

console.log(JSON.stringify(meta));
